s0.initImage("https://upload.wikimedia.org/wikipedia/commons/f/f0/Peregrine_falcon_%28Falco_peregrinus%29%2C.jpg")

let birbs = src(s0)
	.modulateRepeat(noise(1, .1), 2, 3)
	.mult(noise(3, 0.3)
		.modulatePixelate(noise(400, 0.3)
			.contrast(0.1))
		.invert().brightness(-.4))

let sheen = noise(4, 0.5, 0.1)
	.contrast(.5)
	.brightness(-.1)
	.modulateScale(noise(3, .1)
		.kaleid(100))
	.modulateRotate(osc(2))
	.blend(solid(.8, .6, .4), .4)
	.saturate(1.5)

solid(1, 1, 1)
	.layer(birbs)
	.mult(sheen, .8)
	.modulateScale(noise(5, .1), .1)
	.modulate(src(s0)
		.modulateRepeat(noise(1, .1), 2, 3), 0.2)
	.brightness(.2)
	.contrast(1.3)
	.hue(.9)
	.blend(o0, 0.5)
	.out(o0)